title: GitHub Pages
author: Ryan Pitts
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Using this GitHub Page to explore GitHub features.

# social links
github_username:  ryan-pitts

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
